import assert from 'node:assert/strict';
import sharp from 'sharp';
import {randomBytes} from 'node:crypto';
const base=process.argv[2]||'http://localhost:3000';
async function login(email){const r=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password:'Demo123!'})});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];}
async function call(path,cookie,body){const r=await fetch(`${base}/api/${path}`,{method:body===undefined?'GET':'POST',headers:{cookie,...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json();assert.equal(r.status,200,JSON.stringify(j));assert.equal(j.ok,true);return j.data;}
const brand=await login('brand1@demo.local'),creator=await login('creator1@demo.local'),otherBrand=await login('brand2@demo.local'),otherCreator=await login('creator2@demo.local');
const discovered=await call('creators',brand);assert.equal(discovered.count,10);const encoded=JSON.stringify(discovered);for(const secret of ['realName','passwordHash','creator1@demo.local','9000000000'])assert.ok(!encoded.includes(secret));
const brief=await call('briefs',brand,{title:'Acceptance campaign',description:'Unique campaign artwork for a prototype launch.',contentType:'image',style:'Editorial',aspectRatio:'1:1',requiredTools:['Midjourney'],requiredSkills:['Art direction'],budget:'1000.00',deadline:new Date(Date.now()+10*86400000).toISOString().slice(0,10),commercialUse:true,platforms:'Website',duration:'12 months',territory:'Worldwide',exclusivity:false});
const matches=await call(`match/${brief.id}`,brand);assert.equal(matches[0].creator.id,'creator-1');
await call(`briefs/${brief.id}/shortlist`,brand,{creatorId:'creator-1'});
const engagement=await call('invites',brand,{briefId:brief.id,creatorId:'creator-1',message:'Please create our launch visuals.'});
const accepted=await call(`engagements/${engagement.id}`,creator,{action:'accept'});assert.equal(accepted.contract.price,100000);assert.equal(accepted.contract.creatorPayout,90000);
const chat=await call(`messages/${engagement.id}`,creator,{text:'call me on 9876543210 or mail me at a@b.com'});assert.ok(chat.warning);const messages=await call(`messages/${engagement.id}`,brand);assert.ok(!JSON.stringify(messages).includes('9876543210'));assert.ok(!JSON.stringify(messages).includes('a@b.com'));
const form=new FormData();form.set('title','Final visual');form.set('mediaUrl','https://example.org/sample.png');const delivery=await fetch(`${base}/api/deliveries/${engagement.id}`,{method:'POST',headers:{cookie:creator},body:form});assert.equal(delivery.status,200,await delivery.text());
await call(`engagements/${engagement.id}`,brand,{action:'revision'});
const form2=new FormData();form2.set('title','Revised visual');form2.set('mediaUrl','https://example.org/revised.png');assert.equal((await fetch(`${base}/api/deliveries/${engagement.id}`,{method:'POST',headers:{cookie:creator},body:form2})).status,200);
await call(`engagements/${engagement.id}`,brand,{action:'approve'});
const payments=await Promise.all(Array.from({length:5},()=>call('payments',brand,{engagementId:engagement.id})));assert.equal(new Set(payments.map(p=>p.id)).size,1);const invoice=payments[0];assert.equal(invoice.subtotal,100000);assert.equal(invoice.platformFee,10000);assert.equal(invoice.total,110000+invoice.tax);
const bd=await call('dashboard',brand),cd=await call('dashboard',creator);assert.equal(bd.billing.filter(i=>i.engagementId===engagement.id).length,1);assert.equal(cd.billing.filter(i=>i.engagementId===engagement.id).length,1);assert.equal(cd.billing.find(i=>i.engagementId===engagement.id).net,90000);assert.ok(!('payoutId' in (await call(`engagements/${engagement.id}`,brand))));
for(const cookie of [otherBrand,creator,otherCreator]){const r=await fetch(`${base}/api/invoices/${invoice.id}`,{headers:{cookie}});assert.equal(r.status,403);const page=await fetch(`${base}/engagements/${engagement.id}/invoice`,{headers:{cookie}});assert.equal(page.status,403);}
const payout=cd.billing.find(i=>i.engagementId===engagement.id);for(const cookie of [brand,otherBrand,otherCreator]){assert.equal((await fetch(`${base}/api/payouts/${payout.id}`,{headers:{cookie}})).status,403);assert.equal((await fetch(`${base}/engagements/${engagement.id}/payout`,{headers:{cookie}})).status,403);}
for(const doc of [invoice,payout]){assert.ok(!JSON.stringify(doc).includes('@'));assert.ok(!JSON.stringify(doc).includes('Private Creator'));assert.ok(!JSON.stringify(doc).includes('Private Brand'));}
const fallback=await call('brief-builder',brand,{idea:'A video about a new product'});assert.equal(fallback.brief.contentType,'video');assert.equal((await call('creators?q=totally-unmatched',brand)).count,0);
assert.equal((await fetch(`${base}/engagements/${engagement.id}/invoice`,{headers:{cookie:brand}})).status,200);assert.equal((await fetch(`${base}/engagements/${engagement.id}/payout`,{headers:{cookie:creator}})).status,200);
const png=await sharp({create:{width:32,height:32,channels:3,background:{r:randomBytes(1)[0],g:randomBytes(1)[0],b:randomBytes(1)[0]}}}).png().toBuffer();
async function portfolio(cookie){const form=new FormData();for(const [key,value] of Object.entries({title:'Acceptance art experiment',description:'A study of geometry and carefully arranged blocks of colour.',contentType:'image',toolsUsed:'Midjourney',model:'Prototype model',seed:'42',sampler:'Euler',cfg:'7',loras:'None',controlNets:'None',promptStructure:'Shape and colour composition',license:'commercial-safe',modelSource:'Local test'}))form.set(key,value);form.set('file',new Blob([png],{type:'image/png'}),'art.png');const r=await fetch(`${base}/api/portfolio`,{method:'POST',headers:{cookie},body:form});const json=await r.json();assert.equal(r.status,200,JSON.stringify(json));return json.data;}
assert.equal((await portfolio(creator)).published,true);const duplicate=await portfolio(otherCreator);assert.equal(duplicate.published,false);assert.equal(duplicate.plagiarism.status,'Blocked (duplicate)');
console.log('HTTP acceptance passed: matching, shortlist, invite, contract, masking, revision, approval, concurrent idempotent payments, billing privacy, and document API/page 403.');
